name = "hello_world"
version = "0.1.0"

[dependencies]
gleam_bitwise = "~> 1.2"
gleam_otp = "~> 0.7"
gleam_stdlib = "~> 0.32"
simplifile = "~> 0.1"

[dev-dependencies]
exercism_test_runner = "~> 1.4"
